name: KNN Iris Workflow

on:
  push:
    paths:
      - '**.py'
      - 'requirements.txt'
      - 'iris.data'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Train the model
      run: python train.py

    - name: Run prediction
      run: python predict.py
